name: create-post
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: npm install

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Ejecutar index.js
        run: node index.js

      - name: Ejecutar pruebas de Playwright
        uses: microsoft/playwright-github-action@v1
        with:
          browser-type: chromium
          test-command: npm test

      - name: Cargar artefactos de prueba
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: capturas-de-pantalla
          path: screenshots/
