name: create-post
on:
  schedule:
    - cron: "*/1 * * * *" # Ejecutar cada minuto
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14" # Puedes cambiar la versión de Node.js según tus necesidades

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar index.js
        run: node index.js
      
      - name: saludo
        run: echo "Hola mundo"
